/* ============================================================
   REINICIAR_A_CERO_LA_BASE.SQL
   Ubicación: 04_SQLServer_Modelo_Fisico\02_Creacion_de_tablas
   Nota: elimina tablas, pero conserva BaseDeDatos_PyME.
   ============================================================ */
USE BaseDeDatos_PyME;
GO
DROP TABLE IF EXISTS dbo.RECARGOS_FACTURA;
DROP TABLE IF EXISTS dbo.DESCUENTOS_FACTURA;
DROP TABLE IF EXISTS dbo.AUDITORIA_FACTURA;
DROP TABLE IF EXISTS dbo.COMPROBANTES_PAGO;
DROP TABLE IF EXISTS dbo.DETALLES_FACTURA;
DROP TABLE IF EXISTS dbo.FACTURAS;
DROP TABLE IF EXISTS dbo.PRODUCTOS_SERVICIOS;
DROP TABLE IF EXISTS dbo.IMPUESTOS;
DROP TABLE IF EXISTS dbo.CATEGORIAS_PRODUCTO;
DROP TABLE IF EXISTS dbo.FORMAS_PAGO;
DROP TABLE IF EXISTS dbo.TIPOS_OPERACION_FACTURA;
DROP TABLE IF EXISTS dbo.TIPOS_FACTURA;
DROP TABLE IF EXISTS dbo.ESTADOS_FACTURA;
DROP TABLE IF EXISTS dbo.USUARIOS;
DROP TABLE IF EXISTS dbo.CLIENTES;
DROP TABLE IF EXISTS dbo.ESTADOS_CLIENTES;
DROP TABLE IF EXISTS dbo.ESTADOS_USUARIOS;
DROP TABLE IF EXISTS dbo.ROLES;
DROP TABLE IF EXISTS dbo.TIPOS_DOCUMENTO;
DROP TABLE IF EXISTS dbo.TIPOS_CLIENTE;
DROP TABLE IF EXISTS dbo.LOCALIDADES;
DROP TABLE IF EXISTS dbo.PROVINCIAS;
GO
PRINT 'Tablas eliminadas correctamente. La base de datos se conserva.';
GO
