/* ============================================================
   SCRIPT PARA ELIMINAR TODAS LAS TABLAS (orden seguro)
   Proyecto: Gestión de Ventas y Facturación PyME
   ============================================================ */

USE BaseDeDatos_PyME;
GO

SET NOCOUNT ON;
GO

PRINT 'Iniciando eliminación de tablas...';
GO

-- Eliminar tablas con dependencias (orden inverso a creación)
IF OBJECT_ID('dbo.RECARGOS_FACTURA', 'U') IS NOT NULL DROP TABLE dbo.RECARGOS_FACTURA;
IF OBJECT_ID('dbo.DESCUENTOS_FACTURA', 'U') IS NOT NULL DROP TABLE dbo.DESCUENTOS_FACTURA;
IF OBJECT_ID('dbo.AUDITORIA_FACTURA', 'U') IS NOT NULL DROP TABLE dbo.AUDITORIA_FACTURA;
IF OBJECT_ID('dbo.COMPROBANTES_PAGO', 'U') IS NOT NULL DROP TABLE dbo.COMPROBANTES_PAGO;
IF OBJECT_ID('dbo.DETALLES_FACTURA', 'U') IS NOT NULL DROP TABLE dbo.DETALLES_FACTURA;
IF OBJECT_ID('dbo.FACTURAS', 'U') IS NOT NULL DROP TABLE dbo.FACTURAS;
IF OBJECT_ID('dbo.PRODUCTOS_SERVICIOS', 'U') IS NOT NULL DROP TABLE dbo.PRODUCTOS_SERVICIOS;
IF OBJECT_ID('dbo.IMPUESTOS', 'U') IS NOT NULL DROP TABLE dbo.IMPUESTOS;
IF OBJECT_ID('dbo.CATEGORIAS_PRODUCTO', 'U') IS NOT NULL DROP TABLE dbo.CATEGORIAS_PRODUCTO;
IF OBJECT_ID('dbo.USUARIOS', 'U') IS NOT NULL DROP TABLE dbo.USUARIOS;
IF OBJECT_ID('dbo.ESTADOS_USUARIOS', 'U') IS NOT NULL DROP TABLE dbo.ESTADOS_USUARIOS;
IF OBJECT_ID('dbo.ROLES', 'U') IS NOT NULL DROP TABLE dbo.ROLES;
IF OBJECT_ID('dbo.CLIENTES', 'U') IS NOT NULL DROP TABLE dbo.CLIENTES;
IF OBJECT_ID('dbo.TIPOS_CLIENTE', 'U') IS NOT NULL DROP TABLE dbo.TIPOS_CLIENTE;
IF OBJECT_ID('dbo.TIPOS_DOCUMENTO', 'U') IS NOT NULL DROP TABLE dbo.TIPOS_DOCUMENTO;
IF OBJECT_ID('dbo.ESTADOS_CLIENTES', 'U') IS NOT NULL DROP TABLE dbo.ESTADOS_CLIENTES;
IF OBJECT_ID('dbo.LOCALIDADES', 'U') IS NOT NULL DROP TABLE dbo.LOCALIDADES;
IF OBJECT_ID('dbo.PROVINCIAS', 'U') IS NOT NULL DROP TABLE dbo.PROVINCIAS;
IF OBJECT_ID('dbo.FORMAS_PAGO', 'U') IS NOT NULL DROP TABLE dbo.FORMAS_PAGO;
IF OBJECT_ID('dbo.ESTADOS_FACTURA', 'U') IS NOT NULL DROP TABLE dbo.ESTADOS_FACTURA;
IF OBJECT_ID('dbo.TIPOS_FACTURA', 'U') IS NOT NULL DROP TABLE dbo.TIPOS_FACTURA;
IF OBJECT_ID('dbo.TIPOS_OPERACION_FACTURA', 'U') IS NOT NULL DROP TABLE dbo.TIPOS_OPERACION_FACTURA;

PRINT 'Eliminación de tablas completada.';
GO